server:
  port: 9090

spring:
  application:
    name: Identity Service
  profiles:
    active: local

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

roles:
  user: ROLE_USER
  admin: ROLE_ADMIN
  driver: ROLE_DRIVER

