spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/identity_service_db
    username: identity_service
    password: "0000"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: public
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret:
    key: dUM3SDl1VThkWWZKOXNQNW1EMGFMNm5LMnFYMXRSOXlXM3pFOHZNNHBRN3JCMWRGNWhKNnNMOG9UMnZDMHlOMw==
  expiry:
    timeMillis: 3600000 # in milliseconds


app:
  base-url: http://localhost:9090
  support-email: support@shareride.com
  verification-token:
    bytes: 32
    expiry-in-millis: 60000
  rate-limiter:
    email:
      capacity: 5
      refill-tokens: 5
      refill-seconds: 60
    ip:
      capacity: 10
      refill-tokens: 10
      refill-seconds: 60
  email:
    public-domains:
      - email.com
      - gmail.com
      - yahoo.com
      - hotmail.com
      - outlook.com
      - live.com
      - msn.com
      - icloud.com
      - aol.com
      - protonmail.com
      - zoho.com
      - gmx.com
      - yandex.com
      - rediffmail.com
      - naver.com
      - hanmail.net
      - daum.net
      - 163.com
      - 126.com
      - qq.com
      - sina.com
      - web.de
      - t-online.de
      - freenet.de
      - laposte.net
      - libero.it